[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.Localnet]
raydium_cp_swap = "GkenxCtvEabZrwFf15D3E6LjoZTywH2afNwiqDwthyDp"

[programs.Devnet]
raydium_cp_swap = "GkenxCtvEabZrwFf15D3E6LjoZTywH2afNwiqDwthyDp"


[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 10000

[test.validator]
url = "http://127.0.0.1:8899"
